# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBRU4Cjd-tQNOzFYzUQJa0zo-4UP-Ma9
"""

# All CSS in one place so UI modules μένουν καθαρά.
WELCOME_AND_APP_CSS = """
<style>
:root { --font: Inter, system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }
.k-card { width: 520px; border-radius:16px; overflow:hidden; border:1px solid #e6ecf7;
         box-shadow:0 8px 24px rgba(22,27,45,.08); background:#fff; font-family:var(--font); }
.k-head { padding:14px 20px; font-weight:700; background:linear-gradient(120deg,#67b9ff 0%, #84dfd1 100%);
         color:#0f2230; border-bottom:1px solid rgba(255,255,255,.6); }
.k-body { padding:20px 24px; color:#243042; }
.k-input .widget-password input { width:100%; border:1.3px solid #dde3f0; border-radius:12px; padding:10px 12px; font-size:15px; }
.k-input .widget-password input:focus { border-color:#4aa6ff; box-shadow:0 0 0 3px rgba(74,166,255,.15); outline:none; }
.k-btn .widget-button button { width:100%; border-radius:12px; padding:10px 14px; font-weight:600; border:1px solid #1f7ae0; background:#1f7ae0; color:#fff; margin-top:10px; }
.k-btn .widget-button button:hover { box-shadow:0 6px 14px rgba(31,122,224,.25); transform:translateY(-1px); }
.k-ok { padding:10px 12px; border-radius:10px; background:#f3fff6; border:1px solid #bfe9c7; color:#1b5c2b; }
.k-err{ padding:10px 12px; border-radius:10px; background:#fff6f6; border:1px solid #ffd7d7; color:#7a1b1b; }
.k-wrap { border:1px solid #e7e7f2; border-radius:14px; box-shadow:0 6px 18px rgba(0,0,0,.06); }
.k-head2 { display:flex; align-items:center; gap:10px; padding:10px 14px;
  background:linear-gradient(120deg,#67b9ff 0%, #84dfd1 100%); border-bottom:1px solid #e7e7f2; color:#122; font-weight:600; }
.k-textarea textarea { border:1.35px solid #e6e6f0; border-radius:12px; padding:12px; background:#fff; color:#111; font-family:var(--font); font-size:15px; line-height:1.55; font-weight:500; }
.k-textarea textarea:focus { border-color:#4aa6ff; box-shadow:0 0 0 3px rgba(74,166,255,.22); }
.k-pill { background:#f6f7fb; border:1px solid #eceff7; border-radius:999px; padding:3px 10px; font-size:13px; font-weight:500; color:#2e2e55; }
.k-copy { border:1px solid #e7e7f2; background:#fff; padding:6px 10px; border-radius:10px; font-size:13px; cursor:pointer; }
.k-chip { display:inline-block; margin:5px; padding:7px 12px; border-radius:18px; color:#1e1e2e; font-weight:500;
  border:1px solid rgba(0,0,0,0.08); background:linear-gradient(135deg,#f6f9ff,#eef6ff); box-shadow:0 1px 2px rgba(0,0,0,.05); }
@media (prefers-color-scheme: dark){
  .k-card { background:#161a23; border-color:#293246; color:#dee6ef; }
  .k-body { color:#dee6ef; }
}
</style>
"""